name: CI
on: [ pull_request, push, workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGEX_ANSI_COLOR: 's/\x1b\[[0-9;]*[mGKHF]//g'
  REGEX_MAKE_OUTPUT: '/^g*make\[1]: \(Enter\|Leav\)ing directory ''/d'

permissions: {}

jobs:
  build-jvs:
    name: Build jvs keymap
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli@sha256:2dc05fc9f32efebd6b05c2b8676ee548358bc7e151e9dbf4dac6b6eed4513b07
    env:
      CONVERT_TO: rp2040_ce

    steps:
    - name: (actions) Checkout Vial repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive

    - name: Build lily58/rev1:jvs
      id: build
      run: |
        git config --global --add safe.directory $(pwd)
        qmk compile -kb lily58/rev1 -km jvs -e CONVERT_TO=rp2040_ce

    - name: Upload firmware
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: lily58_rev1_jvs_rp2040_ce
        path: .build/lily58_rev1_jvs_rp2040_ce.uf2
